version: "3.8"
services:
  postgres:
    image: postgres:latest
    env_file:
      - portfolio_cemre/docker.env
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    command: -p 5432

  app:
    container_name: app_portfolio_cemre
    hostname: app_portfolio_cemre
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - portfolio_cemre/docker.env
    volumes:
      - .:/srv/app
    ports:
      - "0.0.0.0:8000:8000"
    command: gunicorn portfolio_cemre.wsgi:application --bind 0.0.0.0:8000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres_data:
  static_data:
